[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Adam Woolhether <adamwoolhether@gmail.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
actix-web = "=4.0.1"
actix-http = "=3.0.4"